#!/usr/bin/env python3
"""
Generate gamecube_config.h from JSON config file
"""
import json
import sys
from pathlib import Path

def generate_header(json_path, output_path):
    """Generate C header from JSON config"""

    with open(json_path, 'r') as f:
        config = json.load(f)

    profile_name = config.get('profile_name', 'unknown')
    description = config.get('description', '')
    thresholds = config.get('thresholds', {})
    stick_sensitivity = config.get('stick_sensitivity', {})
    button_mapping = config.get('button_mapping', {})

    header = f"""// Auto-generated from {Path(json_path).name}
// DO NOT EDIT THIS FILE MANUALLY - Edit the JSON config instead

#ifndef GAMECUBE_CONFIG_H
#define GAMECUBE_CONFIG_H

// Profile: {profile_name}
// {description}

// Thresholds
#define GC_L2_DIGITAL_THRESHOLD {thresholds.get('l2_digital', 250)}
#define GC_R2_DIGITAL_THRESHOLD {thresholds.get('r2_digital', 250)}

// Stick sensitivity (1.0 = 100%, 0.6 = 60%, etc.)
#define GC_LEFT_STICK_SENSITIVITY {stick_sensitivity.get('left', 1.0)}f
#define GC_RIGHT_STICK_SENSITIVITY {stick_sensitivity.get('right', 1.0)}f

// Button mapping profile
"""

    # Add button mapping as string defines for documentation
    for button, action in button_mapping.items():
        header += f"#define GC_BUTTON_{button}_ACTION \"{action}\"\n"

    header += """
// Backward compatibility
#define GC_DIGITAL_TRIGGER_THRESHOLD GC_L2_DIGITAL_THRESHOLD

#endif // GAMECUBE_CONFIG_H
"""

    with open(output_path, 'w') as f:
        f.write(header)

    print(f"Generated {output_path} from {json_path}")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.json> <output.h>")
        sys.exit(1)

    generate_header(sys.argv[1], sys.argv[2])
